name: Build

env:
  DOTNET_SDK_VER: 6.0.x
  
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - LICENSE
      - .github/*
      - .gitattributes
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - LICENSE
      - .github/*
      - .gitattributes
jobs:
  test-win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{env.DOTNET_SDK_VER}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  test-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{env.DOTNET_SDK_VER}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-linux:
    runs-on: ubuntu-latest
    needs: [test-win, test-macos]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{env.DOTNET_SDK_VER}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
